# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/k2u/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/htc/k2u/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so \
	vendor/htc/k2u/proprietary/lib/libmmjpeg.so:obj/lib/libmmjpeg.so

PRODUCT_COPY_FILES += \
  vendor/htc/k2u/proprietary/etc/agps_rm:system/etc/agps_rm \
  vendor/htc/k2u/proprietary/bin/dalvik_coredump.sh:system/bin/dalvik_coredump.sh \
  vendor/htc/k2u/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
  vendor/htc/k2u/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
  vendor/htc/k2u/proprietary/lib/bluez-plugin/network.so:system/lib/bluez-plugin/network.so \
  vendor/htc/k2u/proprietary/lib/bluez-plugin/input.so:system/lib/bluez-plugin/input.so \
  vendor/htc/k2u/proprietary/lib/bluez-plugin/bluetooth-health.so:system/lib/bluez-plugin/bluetooth-health.so \
  vendor/htc/k2u/proprietary/lib/bluez-plugin/audio.so:system/lib/bluez-plugin/audio.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ar0260_default_video.so:system/lib/libchromatix_ar0260_default_video.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ar0260_hdr.so:system/lib/libchromatix_ar0260_hdr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ar0260_preview.so:system/lib/libchromatix_ar0260_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ar0260_zsl.so:system/lib/libchromatix_ar0260_zsl.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx091_zsl.so:system/lib/libchromatix_imx091_zsl.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx135_default_video.so:system/lib/libchromatix_imx135_default_video.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx135_hdr.so:system/lib/libchromatix_imx135_hdr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx135_hfr.so:system/lib/libchromatix_imx135_hfr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx135_preview.so:system/lib/libchromatix_imx135_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx135_zsl.so:system/lib/libchromatix_imx135_zsl.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx175_default_video.so:system/lib/libchromatix_imx175_default_video.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx175_hdr.so:system/lib/libchromatix_imx175_hdr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx175_hfr_60fps.so:system/lib/libchromatix_imx175_hfr_60fps.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx175_hfr.so:system/lib/libchromatix_imx175_hfr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx175_preview.so:system/lib/libchromatix_imx175_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_imx175_zsl.so:system/lib/libchromatix_imx175_zsl.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov2722_default_video.so:system/lib/libchromatix_ov2722_default_video.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov2722_preview.so:system/lib/libchromatix_ov2722_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov2722_zsl.so:system/lib/libchromatix_ov2722_zsl.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov5693_default_video.so:system/lib/libchromatix_ov5693_default_video.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov5693_hdr.so:system/lib/libchromatix_ov5693_hdr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov5693_hfr.so:system/lib/libchromatix_ov5693_hfr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov5693_preview.so:system/lib/libchromatix_ov5693_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov5693_zsl.so:system/lib/libchromatix_ov5693_zsl.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov8838_default_video.so:system/lib/libchromatix_ov8838_default_video.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov8838_hdr.so:system/lib/libchromatix_ov8838_hdr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov8838_hfr.so:system/lib/libchromatix_ov8838_hfr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov8838_preview.so:system/lib/libchromatix_ov8838_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_ov8838_zsl.so:system/lib/libchromatix_ov8838_zsl.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k3h2yx_default_video.so:system/lib/libchromatix_s5k3h2yx_default_video.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k3h2yx_hdr.so:system/lib/libchromatix_s5k3h2yx_hdr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k3h2yx_hfr.so:system/lib/libchromatix_s5k3h2yx_hfr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k3h2yx_preview.so:system/lib/libchromatix_s5k3h2yx_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k3h2yx_zsl.so:system/lib/libchromatix_s5k3h2yx_zsl.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k6a1gx_default_video.so:system/lib/libchromatix_s5k6a1gx_default_video.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k6a1gx_hdr.so:system/lib/libchromatix_s5k6a1gx_hdr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k6a1gx_hfr.so:system/lib/libchromatix_s5k6a1gx_hfr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k6a1gx_preview.so:system/lib/libchromatix_s5k6a1gx_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k6a1gx_zsl.so:system/lib/libchromatix_s5k6a1gx_zsl.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k6a2ya_default_video.so:system/lib/libchromatix_s5k6a2ya_default_video.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k6a2ya_hdr.so:system/lib/libchromatix_s5k6a2ya_hdr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k6a2ya_hfr.so:system/lib/libchromatix_s5k6a2ya_hfr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k6a2ya_preview.so:system/lib/libchromatix_s5k6a2ya_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_s5k6a2ya_zsl.so:system/lib/libchromatix_s5k6a2ya_zsl.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_vd6869_default_video.so:system/lib/libchromatix_vd6869_default_video.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_vd6869_hdr.so:system/lib/libchromatix_vd6869_hdr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_vd6869_hfr.so:system/lib/libchromatix_vd6869_hfr.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_vd6869_preview.so:system/lib/libchromatix_vd6869_preview.so \
  vendor/htc/k2u/proprietary/lib/libchromatix_vd6869_zsl.so:system/lib/libchromatix_vd6869_zsl.so \
  vendor/htc/k2u/proprietary/lib/libcameraface.so:system/lib/libcameraface.so \
  vendor/htc/k2u/proprietary/lib/libcamerapp.so:system/lib/libcamerapp.so \
  vendor/htc/k2u/proprietary/lib/libcam_oem_plugin.so:system/lib/libcam_oem_plugin.so \
  vendor/htc/k2u/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/htc/k2u/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
  vendor/htc/k2u/proprietary/lib/libmmcamera_rawchipproc.so:system/lib/libmmcamera_rawchipproc.so \
  vendor/htc/k2u/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/htc/k2u/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/htc/k2u/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/htc/k2u/proprietary/lib/libposteffect.so:system/lib/libposteffect.so \
  vendor/htc/k2u/proprietary/lib/libGLES_direct.so:system/lib/libGLES_direct.so \
  vendor/htc/k2u/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
  vendor/htc/k2u/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
  vendor/htc/k2u/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
  vendor/htc/k2u/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
  vendor/htc/k2u/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
  vendor/htc/k2u/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
  vendor/htc/k2u/proprietary/lib/libc2d2_a3xx.so:system/lib/libc2d2_a3xx.so \
  vendor/htc/k2u/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
  vendor/htc/k2u/proprietary/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
  vendor/htc/k2u/proprietary/lib/libgsl.so:system/lib/libgsl.so \
  vendor/htc/k2u/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
  vendor/htc/k2u/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
  vendor/htc/k2u/proprietary/lib/libsc-a3xx.so:system/lib/libsc-a3xx.so \
  vendor/htc/k2u/proprietary/lib/libOpenCL.so:system/lib/libOpenCL.so \
  vendor/htc/k2u/proprietary/lib/libllvm-a3xx.so:system/lib/libllvm-a3xx.so \
  vendor/htc/k2u/proprietary/lib/libgps.so:system/lib/libgps.so \
  vendor/htc/k2u/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
  vendor/htc/k2u/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
  vendor/htc/k2u/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
  vendor/htc/k2u/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
  vendor/htc/k2u/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
  vendor/htc/k2u/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
  vendor/htc/k2u/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
  vendor/htc/k2u/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
  vendor/htc/k2u/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
  vendor/htc/k2u/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
  vendor/htc/k2u/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
  vendor/htc/k2u/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
  vendor/htc/k2u/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
  vendor/htc/k2u/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
  vendor/htc/k2u/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
  vendor/htc/k2u/proprietary/etc/firmware/fw_bcm4334_p2p.bin:system/etc/firmware/fw_bcm4334_p2p.bin \
  vendor/htc/k2u/proprietary/etc/firmware/fw_bcm4334_apsta.bin:system/etc/firmware/fw_bcm4334_apsta.bin \
  vendor/htc/k2u/proprietary/etc/firmware/fw_bcm4334.bin:system/etc/firmware/fw_bcm4334.bin \
  vendor/htc/k2u/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
  vendor/htc/k2u/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
  vendor/htc/k2u/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
  vendor/htc/k2u/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
  vendor/htc/k2u/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
  vendor/htc/k2u/proprietary/etc/firmware/BCM4334B0_002.001.013.0942.0949.hcd:system/etc/firmware/BCM4334B0_002.001.013.0942.0949.hcd \
  vendor/htc/k2u/proprietary/etc/hldm.bin:system/etc/hldm.bin \
  vendor/htc/k2u/proprietary/etc/hltof.bin:system/etc/hltof.bin \
  vendor/htc/k2u/proprietary/etc/hltrd.bin:system/etc/hltrd.bin \
  vendor/htc/k2u/proprietary/vendor/firmware/mfg.bin:system/vendor/firmware/mfg.bin \
  vendor/htc/k2u/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
  vendor/htc/k2u/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
  vendor/htc/k2u/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
  vendor/htc/k2u/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
  vendor/htc/k2u/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
  vendor/htc/k2u/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin \
  vendor/htc/k2u/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin \
  vendor/htc/k2u/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2/full_model.bin \
  vendor/htc/k2u/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24/full_model.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24/full_model.bin \
  vendor/htc/k2u/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24/full_model.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24/full_model.bin \
  vendor/htc/k2u/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24/full_model.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24/full_model.bin \
  vendor/htc/k2u/proprietary/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N/full_model.bin:system/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N/full_model.bin \
  vendor/htc/k2u/proprietary/lib/libdiag.so:system/lib/libdiag.so \
  vendor/htc/k2u/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
  vendor/htc/k2u/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
  vendor/htc/k2u/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/htc/k2u/proprietary/lib/libqdi.so:system/lib/libqdi.so \
  vendor/htc/k2u/proprietary/lib/libqdp.so:system/lib/libqdp.so \
  vendor/htc/k2u/proprietary/lib/libqmi.so:system/lib/libqmi.so \
  vendor/htc/k2u/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
  vendor/htc/k2u/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
  vendor/htc/k2u/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
  vendor/htc/k2u/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
  vendor/htc/k2u/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
  vendor/htc/k2u/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
  vendor/htc/k2u/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
  vendor/htc/k2u/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
  vendor/htc/k2u/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
  vendor/htc/k2u/proprietary/lib/drm/libhtcomaplugin.so:system/lib/drm/libhtcomaplugin.so \
  vendor/htc/k2u/proprietary/lib/soundfx/libsrsfx.so:system/lib/soundfx/libsrsfx.so

#flashplayer
#  vendor/htc/k2u/proprietary/lib/plugins/com.adobe.flashplayer/libysshared.so:system/lib/plugins/com.adobe.flashplayer/libysshared.so \
#  vendor/htc/k2u/proprietary/lib/plugins/com.adobe.flashplayer/libstagefright_honeycomb.so:system/lib/plugins/com.adobe.flashplayer/libstagefright_honeycomb.so \
#  vendor/htc/k2u/proprietary/lib/plugins/com.adobe.flashplayer/libstagefright_froyo.so:system/lib/plugins/com.adobe.flashplayer/libstagefright_froyo.so \
#  vendor/htc/k2u/proprietary/lib/plugins/com.adobe.flashplayer/libflashplayer.so:system/lib/plugins/com.adobe.flashplayer/libflashplayer.so \

#kernel module
#  vendor/htc/k2u/proprietary/lib/modules/spidev.ko:system/lib/modules/spidev.ko \
#  vendor/htc/k2u/proprietary/lib/modules/scsi_wait_scan.ko:system/lib/modules/scsi_wait_scan.ko \
#  vendor/htc/k2u/proprietary/lib/modules/reset_modem.ko:system/lib/modules/reset_modem.ko \
#  vendor/htc/k2u/proprietary/lib/modules/qcrypto.ko:system/lib/modules/qcrypto.ko \
#  vendor/htc/k2u/proprietary/lib/modules/qcedev.ko:system/lib/modules/qcedev.ko \
#  vendor/htc/k2u/proprietary/lib/modules/qce40.ko:system/lib/modules/qce40.ko \
#  vendor/htc/k2u/proprietary/lib/modules/msm-buspm-dev.ko:system/lib/modules/msm-buspm-dev.ko \
#  vendor/htc/k2u/proprietary/lib/modules/lcd.ko:system/lib/modules/lcd.ko \
#  vendor/htc/k2u/proprietary/lib/modules/ks8851.ko:system/lib/modules/ks8851.ko \
#  vendor/htc/k2u/proprietary/lib/modules/gspca_main.ko:system/lib/modules/gspca_main.ko \
#  vendor/htc/k2u/proprietary/lib/modules/evbug.ko:system/lib/modules/evbug.ko \
#  vendor/htc/k2u/proprietary/lib/modules/eeprom_93cx6.ko:system/lib/modules/eeprom_93cx6.ko \
#  vendor/htc/k2u/proprietary/lib/modules/dma_test.ko:system/lib/modules/dma_test.ko \
#  vendor/htc/k2u/proprietary/lib/modules/bluetooth-power.ko:system/lib/modules/bluetooth-power.ko \
#  vendor/htc/k2u/proprietary/lib/modules/bcmdhd.ko:system/lib/modules/bcmdhd.ko \
#  vendor/htc/k2u/proprietary/lib/modules/ansi_cprng.ko:system/lib/modules/ansi_cprng.ko \
